name: LogiBlocks
main: plugin.bleachisback.LogiBlocks.LogiBlocksMain
version: 1.05
commands:
    command:
        description: Additional command block commands
        usage: /<command> <modifier> [args]...
        aliases: c
    logicif:
        description: If the given flag returns true, executes one command, otherwise it executes the other.
        usage: "/<command> <flag> [args] ? [command if true] : [command if false]"
        aliases: if
    logicfor:
        description: Allows you to use a command multiple times, based on an @e or @p variable.
        usage: /<command> <variable> <repeated command>...
        aliases: for
    phantom:
        permission: c.hidden.phantom
permissions:
    c.craft:
        default: op
        description: Allows user to craft command blocks
    c.edit:
        default: true
        description: Allows user to edit commands inside command blocks
    c.command:
        default: op
        description: Allows user to use commands normally
    c.hidden.phantom:
        default: false